#!/bin/bash
version="1.2.0";
cpSetup_banner() {
	echo -n "${GREEN}"
	cat <<"EOT"
                        ad88888ba
                       d8"     "8b              ,d
                       Y8,                      88
 ,adPPYba, 8b,dPPYba,  `Y8aaaaa,    ,adPPYba, MM88MMM 88       88 8b,dPPYba,
a8"     "" 88P'    "8a   `"""""8b, a8P_____88   88    88       88 88P'    "8a
8b         88       d8         `8b 8PP"""""""   88    88       88 88       d8
"8a,   ,aa 88b,   ,a8" Y8a     a8P "8b,   ,aa   88,   "8a,   ,a88 88b,   ,a8"
 `"Ybbd8"' 88`YbbdP"'   "Y88888P"   `"Ybbd8"'   "Y888  `"YbbdP'Y8 88`YbbdP"'
           88                                                     88
           88                                                     88
EOT
echo -n "${YELLOW}"
	cat <<"EOT"
			 _                  __  __       _
			| |__  _   _    ___|  \/  |_   _| |       ___  ___
			| '_ \| | | |  / __| |\/| | | | | |      / _ \/ __|
			| |_) | |_| |  \__ \ |  | | |_| | |  _  |  __/\__ \
			|_.__/ \__, |  |___/_|  |_|\__, |_| (_)  \___||___/
			       |___/               |___/
EOT
echo -n "${NORMAL}"
}
#                     cPanel Server Setup & Hardening Script
# ------------------------------------------------------------------------------
# @author Myles McNamara
# @date 5.5.2015
# @version 1.2.0
# @source https://github.com/tripflex/cpsetup
# ------------------------------------------------------------------------------
# @usage ./cpsetup [(-h|--help)] [(-v|--verbose)] [(-V|--version)] [(-u|--unattended)]
# ------------------------------------------------------------------------------
# @copyright Copyright (C) 2015 Myles McNamara
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
# ------------------------------------------------------------------------------

# Uncomment out the code below to make the script break on error
# set -e
#
# Functions and Definitions
#
# Define help function
function help(){
    echo "cpsetup - cPanel setup script";
    echo "Usage example:";
    echo "cpsetup [(-h|--help)] [(-v|--verbose)] [(-V|--version)] [(-u|--unattended)] [(-m|--menu)] [(-r|--run) value]";
    echo "Options:";
    echo "-h or --help: Displays this information.";
    echo "-v or --verbose: Verbose mode on.";
    echo "-V or --version: Displays the current version number.";
    echo "-u or --unattended: Unattended installation ( bypasses all prompts ).";
    echo "-m or --menu: Show interactive UI menu.";
    echo "-r or --run: Run a specific function.";
    echo "-R or --functions: Show available functions to use with -r or --run command.";
    exit 1;
}

# Declare vars. Flags initalizing to 0.
verbose="--quiet";
yumargs="";
version=0;
unattended=0;
menu=0;
builddir=~/cpsetupbuild/
sshport=222;
rootemail="your@email.com";
functions=0;

# Execute getopt
ARGS=$(getopt -o "hvVumr:R" -l "help,verbose,version,unattended,menu,run:,functions" -n "cpsetup" -- "$@");

#Bad arguments
if [ $? -ne 0 ];
then
    help;
fi

eval set -- "$ARGS";

while true; do
    case "$1" in
        -h|--help)
            shift;
            help;
            ;;
        -v|--verbose)
            shift;
                    verbose="";
            ;;
        -V|--version)
            shift;
                    echo "$version";
                    exit 1;
            ;;
        -u|--unattended)
            shift;
                    unattended="1";
                    yumargs="-y";
            ;;
        -m|--menu)
            shift;
                    menu="1";
            ;;
        -r|--run)
            shift;
                    if [ -n "$1" ];
                    then
                        runcalled="1";
                        run="$1";
                        shift;
                    fi
            ;;
        -R|--functions)
            shift;
            	functions="1";
            ;;

        --)
            shift;
            break;
            ;;
    esac
done

BLACK=$(tput setaf 0)
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
LIME_YELLOW=$(tput setaf 190)
POWDER_BLUE=$(tput setaf 153)
BLUE=$(tput setaf 4)
MAGENTA=$(tput setaf 5)
CYAN=$(tput setaf 6)
WHITE=$(tput setaf 7)
BRIGHT=$(tput bold)
NORMAL=$(tput sgr0)
BLINK=$(tput blink)
REVERSE=$(tput smso)
UNDERLINE=$(tput smul)

BLACKBG=$(tput setab 0)
REDBG=$(tput setab 1)
GREENBG=$(tput setab 2)
YELLOWBG=$(tput setab 3)
BLUEBG=$(tput setab 4)
MAGENTABG=$(tput setab 5)
CYANBG=$(tput setab 6)
WHITEBG=$(tput setab 7)

function headerBlock {
	l=${#1}
	printf "${BLUE}%s\n%s\n%s\n" "--${1//?/-}--" "${GREEN}- $1 -${BLUE}" "--${1//?/-}--${NORMAL}"
}

function lineBreak {
	echo -e "${MAGENTA}-=========================================================================-${NORMAL}"
}

function givemeayes {
	echo -n "$1 (Y/N)"
	read answer
	    case "$answer" in
	    Y|y|yes|YES|Yes) return 0 ;;
	    *) return 1 ;;
	    esac
}

function stepcheck {
	if (($unattended > 0)); then
		return 0;
	fi

	step=$1
	lineBreak
	if givemeayes "${BRIGHT}Would you like to ${step} ?${NORMAL}"; then
		return 0;
	else
		echo -e "\n${YELLOW}Skipping ${RED}${step}${YELLOW} per user input, continuing...\n${NORMAL}"
		return 1;
	fi

	read answer
	    case "$answer" in
	    Y|y|yes|YES|Yes) return 0 ;;
	    *) echo -e "\n${RED}Skipping this step per user input, processing next step...\n${NORMAL}"; return 1 ;;
	    esac
}

function installClamAV(){
	/scripts/ensurerpm ${verbose} gmp gmp-devel bzip2-devel
	useradd clamav
	groupadd clamav
	mkdir /usr/local/share/clamav
	chown clamav:clamav /usr/local/share/clamav
	cd ~
	wget --no-check-certificate https://github.com/vrtadmin/clamav-devel/archive/clamav-0.98.7.tar.gz
	tar -xzf clamav-*
	rm -rf clamav-*.tar.gz
	cd clamav*
	headerBlock "Building ClamAV from source..."
	./configure --disable-zlib-vcheck ${verbose}
	make ${verbose}
	make install ${verbose}
	headerBlock "Updating configuration files for ClamAV..."
	mv -fv /usr/local/etc/freshclam.conf.sample /usr/local/etc/freshclam.conf
	mv -fv /usr/local/etc/clamd.conf.sample /usr/local/etc/clamd.conf
	sed -i -e 's/Example/#Example/g' /usr/local/etc/freshclam.conf
	sed -i -e 's/Example/#Example/g' /usr/local/etc/clamd.conf
	sed -i -e 's/#LocalSocket/LocalSocket/g' /usr/local/etc/clamd.conf
	sed -i -e 's/clamd.socket/clamd/g' /usr/local/etc/clamd.conf
	ldconfig
	headerBlock "Updating ClamAV definition files..."
	freshclam ${verbose}
	curl http://download.configserver.com/clamd -o /etc/init.d/clamd
	chown root:root /etc/init.d/clamd
	chmod +x /etc/init.d/clamd
	chkconfig clamd on
	service clamd restart
	rm -rf /etc/chkserv.d/clamav
	echo "service[clamav]=x,x,x,service clamd restart,clamd,root" >> /etc/chkserv.d/clamav
	touch /var/log/clam-update.log
	chown clamav:clamav /var/log/clam-update.log
	echo "clamav:1" >> /etc/chkserv.d/chkservd.conf
	rm -rf ~/clamav*
	headerBlock "ClamAV installed, sock will be at /tmp/clamd"
}

function installYumColors(){
	if ! grep -q 'color_list_installed_older' /etc/yum.conf ; then
		echo 'color_list_installed_older=red' >> /etc/yum.conf
	fi
	if ! grep -q 'color_list_installed_newer' /etc/yum.conf ; then
		echo 'color_list_installed_newer=yellow' >> /etc/yum.conf
	fi
	if ! grep -q 'color_list_installed_extra' /etc/yum.conf ; then
		echo 'color_list_installed_extra=red' >> /etc/yum.conf
	fi
	if ! grep -q 'color_list_available_reinstall' /etc/yum.conf ; then
		echo 'color_list_available_reinstall=green' >> /etc/yum.conf
	fi
	if ! grep -q 'color_list_available_upgrade' /etc/yum.conf ; then
		echo 'color_list_available_upgrade=blue' >> /etc/yum.conf
	fi
	if ! grep -q 'color_list_available_install' /etc/yum.conf ; then
		echo 'color_list_available_install=cyan' >> /etc/yum.conf
	fi
}

function installMailManage(){
	cd /usr/src
	rm -fv /usr/src/cmm.tgz
	wget http://download.configserver.com/cmm.tgz
	tar -xzf cmm.tgz
	cd cmm
	sh install.sh
	rm -Rfv /usr/src/cmm*
}

function installMailQueue(){
	cd $builddir
	wget http://download.configserver.com/cmq.tgz
	tar -xzf cmq.tgz
	cd cmq
	sh install.sh
}

function installFirewall(){
	cd $builddir
	wget http://www.configserver.com/free/csf.tgz
	tar -xzf csf.tgz
	cd csf
	sh install.sh
	# Statistical Graphs available from the csf UI
	yum install ${yumargs} perl-GDGraph
	# Check perl modules
	perl /usr/local/csf/bin/csftest.pl
}

function installMalDetect(){
	cd $builddir
	wget --no-check-certificate https://www.rfxn.com/downloads/maldetect-current.tar.gz
	tar -xzf maldetect-*.tar.gz
	rm -rf maldetect-*.tar.gz
	cd maldetect*
	sh install.sh
}

function installSoftaculous(){
	cd $builddir
	wget -N http://files.softaculous.com/install.sh
	chmod 755 install.sh
	./install.sh
}

function installWatchMySQL(){
	cd /usr/src
	wget http://download.ndchost.com/watchmysql/latest-watchmysql
	sh latest-watchmysql
}

function installPHPiniManager(){

	cd /usr/local/cpanel/whostmgr/docroot/cgi
	wget -O addon_phpinimgr.php http://download.how2.be/whm/phpinimgr/addon_phpinimgr.php.txt
	chmod 700 addon_phpinimgr.php

}

function installCleanBackups(){

	cd /usr/src
	wget http://download.ndchost.com/cleanbackups/latest-cleanbackups
	sh latest-cleanbackups

}

function installAccountDNSCheck(){

	cd /usr/src
	wget http://download.ndchost.com/accountdnscheck/latest-accountdnscheck
	sh latest-accountdnscheck

}

function installMySQLTuner(){

	cd /usr/bin
	wget http://mysqltuner.pl/ -O mysqltuner
	chmod +x mysqltuner
}

function hardenServerConfig(){
	# Check server startup for portreserve
	service portreserve stop
	chkconfig portreserve off

	configureApache
	configureCSF
	configureSSH
	configurecPanel
	configurePureFTP
	configureTweakSettings
	configureMySQL
	configurePHP
	csf -r
	/etc/init.d/lfd restart
	/etc/init.d/httpd restart
}

function newCpanelApacheLocalConf(){
cat << 'EOF' > /var/cpanel/conf/apache/local
---
"main":
  "serversignature":
    "item":
      "serversignature": 'Off'
  "servertokens":
    "item":
      "servertokens": 'ProductOnly'
  "traceenable":
    "item":
      "traceenable": 'Off'
EOF
}

function configureApache(){

	if [ ! -f /var/cpanel/conf/apache/local ]; then
		newCpanelApacheLocalConf
		/scripts/rebuildhttpdconf
		/etc/init.d/httpd
	else
		#TODO basic sed replacement
		echo -e "cPanel Apache Local Configuration file ( /var/cpanel/conf/apache/local ) already exists, unable to update"
	fi
}

function configureCSF(){
	sed -i -e 's/RESTRICT_SYSLOG = "0"/RESTRICT_SYSLOG = "3"/g' /etc/csf/csf.conf
	sed -i -e 's/SMTP_BLOCK = "0"/SMTP_BLOCK = "1"/g' /etc/csf/csf.conf
	sed -i -e 's/LF_SCRIPT_ALERT = "0"/LF_SCRIPT_ALERT = "1"/g' /etc/csf/csf.conf
	sed -i -e 's/SYSLOG_CHECK = "0"/SYSLOG_CHECK = "1800"/g' /etc/csf/csf.conf
	sed -i -e 's/PT_ALL_USERS = "0"/PT_ALL_USERS = "1"/g' /etc/csf/csf.conf

}

function configureSSH(){
	sed -i -e "s/#Port 22/Port ${sshport}/g" /etc/ssh/sshd_config
	sed -i -e 's/#UseDNS yes/UseDNS no/g' /etc/ssh/sshd_config
	/etc/init.d/sshd restart
}

function configurecPanel(){
	# Enable Shell Fork Bomb Protection
	perl -I/usr/local/cpanel -MCpanel::LoginProfile -le 'print [Cpanel::LoginProfile::install_profile('limits')]->[1];'
	# Compiler access
	chmod 750 /usr/bin/gcc
	# Root Forwarder
	if [ ! -f /root/.forward ]; then
    	echo $rootemail > /root/.forward
	fi
}

function configurePureFTP(){
	sed -i -e "s/RootPassLogins: 'yes'/RootPassLogins: 'no'/g" /var/cpanel/conf/pureftpd/main
	sed -i -e "s/AnonymousCantUpload: 'no'/AnonymousCantUpload: 'yes'/g" /var/cpanel/conf/pureftpd/main
	sed -i -e "s/NoAnonymous: 'no'/NoAnonymous: 'yes'/g" /var/cpanel/conf/pureftpd/main
	# Build configuration from cPanel FTP config
	/usr/local/cpanel/whostmgr/bin/whostmgr2 doftpconfiguration > /dev/null
}

function configureTweakSettings(){
	sed -i -e 's/skipboxtrapper=0/skipboxtrapper=1/g' /var/cpanel/cpanel.config
	sed -i -e 's/referrerblanksafety=0/referrerblanksafety=1/g' /var/cpanel/cpanel.config
	sed -i -e 's/referrersafety=0/referrersafety=1/g' /var/cpanel/cpanel.config
	sed -i -e 's/cgihidepass=0/cgihidepass=1/g' /var/cpanel/cpanel.config
	echo "maxemailsperhour=199" >> /var/cpanel/cpanel.config
	# Must be ran after updating tweak settings file
	/usr/local/cpanel/whostmgr/bin/whostmgr2 --updatetweaksettings > /dev/null
}

function configureMySQL(){
	if ! grep -q 'local-infile=0' /etc/yum.conf ; then
		echo 'local-infile=0' >> /etc/my.cnf
		/scripts/restartsrv_mysql
	fi
}

function configurePHP(){
	sed -i -e 's/enable_dl = On/enable_dl = Off/g' /usr/local/lib/php.ini
	sed -i -e 's/disable_functions =/disable_functions = show_source, system, shell_exec, passthru, exec, phpinfo, popen, proc_open, allow_url_fopen, ini_set/g' /usr/local/lib/php.ini
}

function promptForSSHPort(){
	# Configuration Prompts ( only shown when -u is NOT specified )
	if (($unattended < 1)); then
		echo -n "${MAGENTA}Enter SSH port to change from ${BLUE}${sshport}${MAGENTA}:${NORMAL} "
		read customsshport
		if [ $customsshport ]; then
			sshport=$customsshport
		fi
	fi
}

function promptForRootForwardEmail(){
	# Configuration Prompts ( only shown when -u is NOT specified )
	if (($unattended < 1)); then

		echo -n "${MAGENTA}Enter root forwarding email to change from ${BLUE}${rootemail}${MAGENTA}:${NORMAL} "
		read customrootemail
		if [ $customrootemail ]; then rootemail=$customrootemail
		fi

	fi
}

clear
cpSetup_banner
echo -e "\n";

if (($functions > 0)); then
	echo -e "${RED}Here's a list of available functions to call when using the -r or --run command:${NORMAL}"
	echo -e "\n";
	compgen -A function | egrep -vw 'givemeayes|help|headerBlock|lineBreak|stepcheck|promptForSSHPort|promptForRootForwardEmail|cpSetup_banner';
	echo -e "\n";
	exit;
fi

echo -e "${WHITEBG}${RED}${BRIGHT}${BLINK}Heads Up!${NORMAL}${WHITEBG}${BLACK}There's a few things you should make sure of before running this script:${NORMAL}"
echo -e "* You must have ${YELLOW}ioncube${NORMAL} enabled in ${YELLOW}WHM${NORMAL} under ${BLUE}Tweak Settings${NORMAL} > ${MAGENTA}cPanel PHP Loader${NORMAL} or Softaculous will not install"
echo -e "* You must go through the initial setup in ${YELLOW}WHM${NORMAL}, selecting dns and ftp server type (when you first login to WHM) before running this script."
echo -e "${BLUE}Like the script?  Contribute to the open source community and this project at http://github.com/tripflex/cpsetup ... surfs up!${NORMAL}"
echo -e "\n";

if (($unattended > 0)); then
	echo -e "${YELLOW}!!! WARNING: Unattended mode ENABLED, you will not be prompted for each install/configuration !!!${NORMAL}"
fi

if [ $run ]; then
	echo -e "${YELLOW}RUN command specified, only the${RED} $run ${YELLOW}function will be executed. ${NORMAL}"
fi

echo -e "\n";

if ! givemeayes "${RED}Would you like to continue with the install?${NORMAL}"; then
	echo -e "\n${RED}Script killed, nothing has been changed or installed.\n${NORMAL}"
	exit;
fi

if [ -d "$builddir" ]; then
	rm -rf $builddir
fi

mkdir $builddir

if [ $run ]; then
	${run}
	exit;
fi

if stepcheck "install yum colors"; then
	headerBlock "Adding yum colors if does not exist..."
	installYumColors
fi

if stepcheck "update all server packages"; then
	headerBlock "Updating all system packages, please wait this may take a minute..."
	yum clean all ${verbose}
	yum update ${yumargs} ${verbose}
fi

if stepcheck "install ConfigServer MailManage"; then
	headerBlock "Installing ConfigServer MailManage, please wait..."
	installMailManage
fi

if stepcheck "install ConfigServer MailQueue"; then
	headerBlock "Installing ConfigServer MailQueue, please wait..."
	installMailQueue
fi

if stepcheck "install ConfigServer Firewall"; then
	headerBlock "Installing ConfigServer Firewall, please wait..."
	installFirewall
fi

if stepcheck "install R-fx Malware Detect"; then
	headerBlock "Installing R-fx Malware Detect, please wait..."
	installMalDetect
fi

echo -n "${YELLOW}Just a heads up${RED}( do this NOW ): ${NORMAL}You must have ${YELLOW}ioncube${NORMAL} enabled in ${YELLOW}WHM${NORMAL} under ${BLUE}Tweak Settings${NORMAL} > ${MAGENTA}cPanel PHP Loader${NORMAL} or Softaculous will not install"
echo -e "\n";
if stepcheck "install Softaculous"; then
	headerBlock "Installing Softaculous, please wait..."
	installSoftaculous
fi

if stepcheck "install Account DNS Check"; then
	headerBlock "Installing Account DNS Check, please wait..."
	installAccountDNSCheck
fi

if stepcheck "install WatchMySQL"; then
	headerBlock "Installing WatchMySQL, please wait..."
	installWatchMySQL
fi

if stepcheck "install PHP.INI Manager"; then
	headerBlock "Installing PHP.INI Manager, please wait..."
	installPHPiniManager
fi

if stepcheck "install Clean Backups"; then
	headerBlock "Installing Clean Backups, please wait..."
	installCleanBackups
fi

if stepcheck "install MySQL Tuner"; then
	headerBlock "Installing MySQL Tuner, please wait..."
	installCleanBackups
fi

if stepcheck "harden server configuration"; then
	promptForSSHPort
	promptForRootForwardEmail
	headerBlock "Securing the server with configuration tweaks, please wait..."
	hardenServerConfig
fi

if stepcheck "install ClamAV from source"; then
	headerBlock "Installing ClamAV from source, please wait..."
	installClamAV
fi

headerBlock "Cleaning up build files, please wait..."
cd ~
rm -rf $builddir
echo -e "\n${CYAN}Script Complete! Profit!\n${NORMAL}"